# Generated by Django 4.2.2 on 2023-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('IdEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
