# Generated by Django 4.2.2 on 2023-06-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idautor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('idcredenciales', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('ideditorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('idencargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('credenciales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.credenciales')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idlibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('año_publicacion', models.PositiveIntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idprestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.encargado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('idpenalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('iddevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo')),
            ],
        ),
    ]
